// template/src/framework/vue/Store.vue
<script setup lang="ts">
import { useStore } from "@nanostores/vue";

import VueLogo from "../../images/vue.png?url";
import { framework } from "../../stores/framework";

const selectedFramework = useStore(framework);

const setFramework = () => {
  framework.set("Vue");
};
</script>

<template>
  <div class="card">
    <strong>Vue Store</strong>
    <div class="card-content">
      <img alt="Vue logo" :src="VueLogo" height="150" />
      <div>
        <strong>Value:</strong>
        <div id="nanostore">{{ selectedFramework }}</div>
      </div>
      <div>
        <button class="card-btn" @click="setFramework">Select Vue</button>
      </div>
    </div>
  </div>
</template>

// template/src/framework/react/Store.tsx
/** @jsxImportSource react */
import { useStore } from "@nanostores/react";

import ReactLogo from "../../images/react.png?url";
import { framework } from "../../stores/framework";

export default function Store() {
  const selectedFramework = useStore(framework);

  const setFramework = () => {
    framework.set("React");
  };

  return (
    <div className="card">
      <strong>React Store</strong>
      <div className="card-content">
        <img alt="React logo" height={150} src={ReactLogo} />
        <div>
          <strong>Value:</strong>
          <div id="nanostore">{selectedFramework}</div>
        </div>
        <div>
          <button className="card-btn" onClick={setFramework}>
            Select React
          </button>
        </div>
      </div>
    </div>
  );
}
