// integrations/qwik/client.ts
/**
 * Client entrypoint for the Qwik renderer.
 *
 * `@qwik.dev/astro` ships a server entrypoint only, so Astro emits an
 * `<astro-island>` with no `renderer-url` and no serialized `props`, and the
 * island runtime falls back to a no-op hydrator. Qwik islands are used with
 * `client:only`, so there is no server-rendered container to resume: this
 * entrypoint renders the component on the client, and again whenever the
 * props change.
 */
import { jsx, type JSXNode, render } from "@qwik.dev/core";
import { QWIK_LOADER } from "@qwik.dev/core/loader";

/** Holds the slot content, which Astro's island runtime hands over only once. */
const SLOTS = Symbol.for("islands/qwik/slots");

type IslandElement = {
  [SLOTS]?: Record<string, string>;
} & HTMLElement;

/**
 * Installs the qwikloader, which delegates DOM events to Qwik handlers.
 *
 * A server-rendered page gets this from Qwik's own build, but an island that
 * renders on the client has no such script, so its handlers never fire.
 * Qwik registers the event names it needs on `window._qwikEv` as it renders;
 * the loader picks them up. It no-ops if another loader already claimed
 * `_qwikEv`, so calling this more than once is safe.
 */
function ensureQwikLoader(): void {
  const script = document.createElement("script");
  script.setAttribute("qwik-loader", "");
  script.textContent = QWIK_LOADER;
  document.head.appendChild(script);
}

/**
 * Rebuilds Astro's slot content as Qwik children. Named slots are projected
 * with `q:slot`, matching what `<Slot name="..." />` expects.
 */
function toChildren(slotted: Record<string, string>): JSXNode[] {
  return Object.entries(slotted).map(([name, html]) =>
    jsx("astro-slot", {
      dangerouslySetInnerHTML: html,
      ...(name === "default" ? {} : { "q:slot": name }),
    }),
  );
}

const client_default =
  (element: IslandElement) =>
  async (
    Component: unknown,
    props: Record<string, unknown>,
    slotted: Record<string, string>,
    { client }: { client: string },
  ) => {
    if (client !== "only" && !element.hasAttribute("ssr")) return;

    // Astro's island runtime reads the slot templates out of the DOM and
    // removes them, so it only ever passes them in once. Keep them, or a later
    // render — a props update, say — would drop the slot content.
    if (Object.keys(slotted).length > 0) element[SLOTS] = slotted;

    if (typeof Component !== "function") return;

    // A props update replaces the previous render.
    element.innerHTML = "";
    element.removeAttribute("q:container");
    ensureQwikLoader();

    await render(
      element,
      jsx(Component as Parameters<typeof jsx>[0], {
        ...props,
        children: toChildren(element[SLOTS] ?? {}),
      }),
      { serverData: props },
    );
  };

export default client_default;

// integrations/lit/client.ts
/** The Lit element rendered into the island. */
const ELEMENT = Symbol.for("islands/lit/element");
/** The props last set on that element. */
const PROPS = Symbol.for("islands/lit/props");

type IslandElement = {
  [ELEMENT]?: HTMLElement;
  [PROPS]?: Record<string, unknown>;
} & HTMLElement;

let anonymousCount = 0;

/**
 * Creates the custom element for a Lit class. A class the module registered
 * with `customElements.define` keeps its tag; one that was never registered
 * gets a generated tag, since a custom element cannot be created without one.
 */
function createElement(Component: CustomElementConstructor): HTMLElement {
  const name = customElements.getName?.(Component);
  if (name) return document.createElement(name);

  try {
    return new Component();
  } catch {
    let tag: string;
    do {
      tag = `islands-lit-${++anonymousCount}`;
    } while (customElements.get(tag));
    customElements.define(tag, Component);
    return document.createElement(tag);
  }
}

/**
 * Moves the Astro slots into the element's light DOM. Each slot is wrapped in
 * an `<astro-slot>` (styled `display: contents` by Astro), and a named one
 * gets the matching `slot` attribute so the shadow `<slot name>` shows it.
 */
function projectSlots(element: HTMLElement, slotted: Record<string, string>) {
  for (const [name, html] of Object.entries(slotted)) {
    const slot = document.createElement("astro-slot");
    if (name !== "default") slot.setAttribute("slot", name);
    slot.innerHTML = html;
    element.appendChild(slot);
  }
}

/** Sets the props as element properties, which Lit re-renders from. */
function setProps(
  element: HTMLElement,
  props: Record<string, unknown>,
  previous: Record<string, unknown> = {},
) {
  const target = element as unknown as Record<string, unknown>;
  for (const key of Object.keys(previous)) {
    if (!(key in props)) target[key] = undefined;
  }
  Object.assign(target, props);
}

const client_default =
  (element: IslandElement) =>
  (
    Component: unknown,
    props: Record<string, unknown>,
    slotted: Record<string, string>,
  ) => {
    // The island runtime and the OutSystems Islands module both set `ssr` when
    // they want the island (re-)rendered. Without it there is nothing to do.
    if (!element.hasAttribute("ssr")) return;
    if (typeof Component !== "function") return;

    // A props update only has to reach the element's properties: Lit
    // re-renders what reads them, and internal state such as a count is kept.
    const existing = element[ELEMENT];
    if (existing) {
      setProps(existing, props, element[PROPS]);
      element[PROPS] = { ...props };
      return;
    }

    const litElement = createElement(Component as CustomElementConstructor);
    setProps(litElement, props);
    projectSlots(litElement, slotted);

    element[ELEMENT] = litElement;
    element[PROPS] = { ...props };
    element.replaceChildren(litElement);
  };

export default client_default;
