// template/src/framework/svelte/Store.svelte
<script lang="ts">
  import SvelteLogo from "../../images/svelte.png?url";
  import { framework } from "../../stores/framework";

  const setFramework = () => {
    framework.set("Svelte");
  };
</script>

<div class="card">
  <strong>Svelte Store</strong>
  <div class="card-content">
    <img alt="Svelte logo" src={SvelteLogo} height="150" />
    <div>
      <strong>Value:</strong>
      <div id="nanostore">{$framework}</div>
    </div>
    <div>
      <button class="card-btn" on:click={setFramework}>Select Svelte</button>
    </div>
  </div>
</div>

// template/src/framework/vue/Store.vue
<script setup lang="ts">
import { useStore } from "@nanostores/vue";

import VueLogo from "../../images/vue.png?url";
import { framework } from "../../stores/framework";

const selectedFramework = useStore(framework);

const setFramework = () => {
  framework.set("Vue");
};
</script>

<template>
  <div class="card">
    <strong>Vue Store</strong>
    <div class="card-content">
      <img alt="Vue logo" :src="VueLogo" height="150" />
      <div>
        <strong>Value:</strong>
        <div id="nanostore">{{ selectedFramework }}</div>
      </div>
      <div>
        <button class="card-btn" @click="setFramework">Select Vue</button>
      </div>
    </div>
  </div>
</template>
