// template/src/framework/angular/Store.component.ts
import { CommonModule } from "@angular/common";
import { Component } from "@angular/core";

import AngularLogo from "../../images/angular.png?url";

@Component({
  imports: [CommonModule],
  selector: "app-counter",
  standalone: true,
  template: `
    <div class="card unused">
      <strong>Angular Store</strong>
      <div class="card-content">
        <img [src]="angularLogo" alt="Angular logo" height="150" />
        <div>
          <strong>Angular 21 does not currently support Nano Stores.</strong>
        </div>
      </div>
    </div>
  `,
})
export default class StoreComponent {
  angularLogo = AngularLogo;
}

// template/src/framework/qwik/Store.tsx
/** @jsxImportSource @qwik.dev/core */
import { component$ } from "@qwik.dev/core";

import QwikLogo from "../../images/qwik.png?url";

export default component$(() => {
  return (
    <div class="card unused">
      <strong>Qwik Store</strong>
      <div class="card-content">
        <img alt="Qwik logo" height={150} src={QwikLogo} />
        <div>
          <strong>Qwik does not currently support Nano Stores.</strong>
        </div>
      </div>
    </div>
  );
});
