// template/src/framework/stencil/Store.tsx
/** @jsxImportSource @stencil/core */
import { Component } from "@stencil/core";

import StencilLogo from "../../images/stencil.png?url";
import styles from "../../styles/index.css?inline";

@Component({ shadow: true, styles, tag: "stencil-store" })
export default class Store {
  render() {
    return (
      <div class="card unused">
        <strong>Stencil Store</strong>
        <div class="card-content">
          <img alt="Stencil logo" height="150" src={StencilLogo} />
          <div>
            <strong>
              Stencil does not have an official Nano Stores implementation.
            </strong>
          </div>
        </div>
      </div>
    );
  }
}

// template/src/framework/qwik/Store.tsx
/** @jsxImportSource @qwik.dev/core */
import { component$ } from "@qwik.dev/core";

import QwikLogo from "../../images/qwik.png?url";

export default component$(() => {
  return (
    <div class="card unused">
      <strong>Qwik Store</strong>
      <div class="card-content">
        <img alt="Qwik logo" height={150} src={QwikLogo} width={146} />
        <div>
          <strong>
            Qwik does not have an official Nano Stores implementation.
          </strong>
        </div>
      </div>
    </div>
  );
});
