// template/src/framework/solid/Demo.tsx
/** @jsxImportSource solid-js */
import { useStore } from "@nanostores/solid";
import { createSignal, type JSX } from "solid-js";

import AstroLogo from "../../images/astro.png?url";
import OutSystemsLogo from "../../images/outsystems.png?url";
import { Operation, setCounterCount } from "../../lib/setCounterCount";
import { setupStore } from "../../stores/demo";

interface DemoProps {
  children?: JSX.Element;
  header?: JSX.Element;
  initialCount: number;
  showMessage: string;
}

export default function Demo(props: DemoProps) {
  const [count, setCount] = createSignal(props.initialCount);

  const store = setupStore("solidStore");
  const nanoStoreValue = useStore(store);

  const add = () => setCount((i) => setCounterCount(i, Operation.Add));
  const subtract = () =>
    setCount((i) => setCounterCount(i, Operation.Subtract));

  const showParentMessage = () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const messageFunc = (window as any)[props.showMessage];
    if (typeof messageFunc === "function") {
      messageFunc(count());
    }
  };

  return (
    <>
      {props.header}

      <div class="card-grid">
        <div class="card">
          <strong>Solid counter component</strong>
          <div class="card-content">
            Internal counter controls. It keeps state within the component.
            <div class="counter-controls">
              <button onClick={subtract}>-</button>
              <pre>{count()}</pre>
              <button onClick={add}>+</button>
            </div>
          </div>
          The button sends the current count value to a function in the parent
          component.
          <div class="card-content">
            <div>
              <button class="card-btn" onClick={showParentMessage}>
                Send value
              </button>
            </div>
          </div>
        </div>

        <div class="card">
          <strong>Nano Stores</strong>
          <div class="card-content">
            <div>
              <strong>Value:</strong>
              <div id="nanostore">{nanoStoreValue()}</div>
            </div>
          </div>
        </div>

        <div class="card">
          <strong>Slot content</strong>
          <div class="card-content">
            <div>{props.children}</div>
          </div>
        </div>
      </div>

      <div class="counter-logos">
        <img alt="OutSystems logo" src={OutSystemsLogo} />
        <img alt="Astro logo" src={AstroLogo} />
      </div>
    </>
  );
}

// template/src/framework/preact/Demo.tsx
/** @jsxImportSource preact */
import { useStore } from "@nanostores/preact";
import type { ComponentChildren } from "preact";
import { useState } from "preact/hooks";

import AstroLogo from "../../images/astro.png?url";
import OutSystemsLogo from "../../images/outsystems.png?url";
import { Operation, setCounterCount } from "../../lib/setCounterCount";
import { setupStore } from "../../stores/demo";

interface DemoProps {
  children: ComponentChildren;
  header: ComponentChildren;
  initialCount: number;
  showMessage: string;
}

export default function Demo({
  children,
  header,
  initialCount,
  showMessage,
}: DemoProps) {
  const [count, setCount] = useState(initialCount);

  const add = () => setCount((i) => setCounterCount(i, Operation.Add));

  const subtract = () =>
    setCount((i) => setCounterCount(i, Operation.Subtract));

  const showParentMessage = () => {
    if (typeof window !== "undefined") {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (window as any)[showMessage](count);
    }
  };

  const store = setupStore("preactStore");

  const nanoStoreValue = useStore(store);

  return (
    <>
      {header}
      <div className="card-grid">
        <div className="card">
          <strong>Preact counter component</strong>
          <div className="card-content">
            Internal counter controls. It keeps state within the component.
            <div className="counter-controls">
              <button onClick={subtract}>-</button>
              <pre>{count}</pre>
              <button onClick={add}>+</button>
            </div>
          </div>
          The button sends the current count value to a function in the parent
          component.
          <div className="card-content">
            <div>
              <button className="card-btn" onClick={showParentMessage}>
                Send value
              </button>
            </div>
          </div>
        </div>
        <div className="card">
          <strong>Nano Stores</strong>
          <div className="card-content">
            <div>
              <strong>Value:</strong>
              <div id="nanostore">{nanoStoreValue}</div>
            </div>
          </div>
        </div>
        <div className="card">
          <strong>Slot content</strong>
          <div className="card-content">
            <div>{children}</div>
          </div>
        </div>
      </div>
      <div className="counter-logos">
        <img alt="OutSystems logo" src={OutSystemsLogo} />
        <img alt="Astro logo" src={AstroLogo} />
      </div>
    </>
  );
}
